/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, Html } from "@react-three/drei";
// import Text from "./Text"

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/card.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <planeBufferGeometry args={[props.width, props.height]} />
      <mesh
        geometry={nodes.Glass_Card.geometry}
        material={materials["Caribbean Balm 2"]}
        position={[0, 0, 0.1]}
        // rotation={[0, 0.99224463, -Math.PI / 2]}
        rotation={[0, props.yRotation, -Math.PI / 2]}
        scale={[0.0015 , 0.002 , 0.0025]}
      />
      
    </group>
  );
}

useGLTF.preload("/card.glb");
