/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useScroll, Scroll, useGLTF, useAnimations, useAspect, Image } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { TextAnimation } from './TextAnimation'

export default function Model(props) {
  const group = useRef()
  const imgRef = useRef()
  const size = useAspect(1800, 1000)

  // This hook gives you offets, ranges and other useful things
  const scroll = useScroll()
  const { scene, nodes, animations, materials } = useGLTF('/emerald.glb')
  const { actions } = useAnimations(animations, scene)
  
  useFrame((state, delta) => {
    // The offset is between 0 and 1, you can apply it to your models any way you like
    const offset = 1 - scroll.offset

    // console.log('offset', offset)
    // console.log('scrolloffset', scroll.offset)
    
    const model = group.current;

    model.rotation.y = offset * 30.7
    model.position.y = (-37 + (offset * 45)) / 5
  })

  return (
        <>
        <Image url="/Home.png" 
        // position={[0,0,-3]}
        scale={size}
          transparent
          opacity={0.3} 
        />
         <group ref={group} position={[2, -4, -8]} rotation={[0, 2, 0]} scale={8}>
          <mesh castShadow receiveShadow geometry={nodes.emeraldbot_1.geometry}  material-color={"#00FFD9"} />
          <mesh castShadow receiveShadow geometry={nodes.emeraldbot_2.geometry} material={materials['flowbot:phong2']} />
          <mesh castShadow receiveShadow geometry={nodes.emeraldbot_3.geometry} material={materials['flowbot:phong3']} />
          <mesh castShadow receiveShadow geometry={nodes.emeraldbot_4.geometry} material-color={"#2FD1B9"} />
        </group>
        </>
       
  )
}

useGLTF.preload('/emerald.glb')